<a href="https://colab.research.google.com/github/muhammad-ahmad-github/learning-pytorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Python Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.0.1+cu118


## Introduction to Tensors

Creating Tensors

In [3]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor (([7,8],
                       [9,10]))
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why Random Sensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numners and then adjust those random numbers to better represent the data.

 ```Start with random numbers -> look at dat -> update random numbers -> look at data -> update random numbers```


In [23]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.2893, 0.8800, 0.9671, 0.7289],
         [0.5648, 0.1681, 0.6327, 0.3362],
         [0.1907, 0.9164, 0.4910, 0.5737]]])

In [24]:
random_tensor.ndim

3

In [32]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 224,224)) # color, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [33]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [35]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [41]:
# Use torch.range() gets deprecated message, use torch.arange()

one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
#one_to_ten = torch.arange(start=10, end= 21, step=1)
#one_to_ten

# o/p tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with Pytorch and Deep Learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [51]:
# Float 32 tensor

float_32_tensor = torch.tensor ([3.0, 6.0, 9.0],
                                dtype=None,           # What datatype is the tensor (e.g torch.float16, torch.float32)
                                device=None,          # "cpu" / "cuda"
                                requires_grad=False )   # Pytorch tracks Gradients or not with Tensor)
float_32_tensor

tensor([3., 6., 9.])

In [52]:
float_32_tensor.dtype

torch.float32

In [53]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from Tensors Attributes

1. Tensors not right datatype - to get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shapre from tensor, can use tensor.shape
3. Tensors not on right device - to get device from tensor, can ue tensor.device

In [54]:
# Create a tensor

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8116, 0.4569, 0.1743, 0.8702],
        [0.9599, 0.9133, 0.9193, 0.4480],
        [0.4737, 0.3013, 0.6605, 0.3765]])

In [57]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: :{some_tensor.device}")

tensor([[0.8116, 0.4569, 0.1743, 0.8702],
        [0.9599, 0.9133, 0.9193, 0.4480],
        [0.4737, 0.3013, 0.6605, 0.3765]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: :cpu


### Manipulating Tensors (tensor opertions)

Tensor operations includes:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [61]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [60]:
# Multiply tensor by 10

tensor * 10

tensor([10, 20, 30])

In [62]:
# Subtract 10

tensor - 10

tensor([-9, -8, -7])

In [63]:
# TRY out Pytorch in-built fn

torch.mul(tensor,10)

tensor([10, 20, 30])

In [64]:
torch.add(tensor, 15)

tensor([16, 17, 18])

### Matrix Multiplication

Two main ways of performing multiplication in Neural Networks and DeepLearning

1. Element wise multiplication
2. Matrix Multiplication

There are two mail rules that performing matrix multiplicatication needs to satisfy:
1. The **inner dimension** must match
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work

* @ AND matmul AND matmm are same

In [66]:
# Element wise multiplication

print (tensor,"*", tensor)
print (f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [67]:
# MAtrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [68]:
# Multiplication by hand
1*1 + 2*2 + 3*3

14

In [71]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.15 ms, sys: 9 µs, total: 1.15 ms
Wall time: 965 µs


tensor(14)

In [72]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 52 µs, sys: 4 µs, total: 56 µs
Wall time: 58.7 µs


tensor(14)

### One of the most common errors in DeepLearning: Shape errors

In [77]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm (tensor_A, tensor_B)  # torch.mm is the same as torch.matmul (its an alias for writing less code)

#torch.matmul (tensor_A, tensor_B)

To fix our tensor shape issues, we can use Transpose
Tensor_B.T

In [76]:
tensor_B.T, tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([3, 2]))

In [81]:
torch.matmul (tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Finding the min, max, mean, sum, etc (Tensor Aggregation)

In [86]:
# Create tensor

x= torch.arange (0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [84]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [85]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [88]:
# Find the mean
# NOTE: THE TORCH.MEAN() FN REQUIRES A TENSOR OF FLOAT32 DATATYPE TO WORK

# torch.mean(x)
# Not working as x is int-64 and mean doesnt work on it

# convert x type

torch.mean (x.type(torch.float32)),  x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [89]:
# fIND THE SUM

torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [94]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [95]:
# Find the position in tensor that has min value with argmin() -> return the index position of targettensor where min value occurs
x.argmin()

tensor(0)

In [96]:
# Find the position in tensor that has the max value with argmax()
x.argmax()

tensor(9)

### Reshaping, stacking, sqeezing and unsqeazing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of input tensor of certain shape but keep the same memory s the original tensor
* Stacking - combine multiple tensors on top of eachother (vstack) or side-by-side (hstack)
* Sqeeze - removes all '1' dimension from tensor
* Unsqeeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in certain way

In [15]:
# Lets create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [16]:
# Add an extra dimension

x_reshaped = x.reshape (1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [5]:
x_reshaped = x.reshape (9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [17]:
#Change the view

z= x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [18]:
# NOTE: CHANGING Z CHANGES X (because view of tensor same menomry as the original tensor)

z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [19]:
# Stack tensors on top of eachother

x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [21]:
# Torch sqeezed - remove all single dinmensions from a target sensor

print (f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Rmove extra dimensions from x_shaped
x_sqeezed = x_reshaped.squeeze()
print (f"\n New Tensor: {x_sqeezed}")
print(f"New Shape: {x_sqeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

 New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [13]:
x_reshaped.squeeze().shape

torch.Size([9])

In [25]:
# torch.unsqeeze() - adds a sngle dimension to a target tensor at a specific dim
print(f"Previous target: {x_sqeezed}")
print (f"Previous shape: {x_sqeezed.shape}")

#ADD an extra dimension with unsqeeze
x_unsqueezed = x_sqeezed.unsqueeze(dim=0)
print(f"\n New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [27]:
# torch.permute - Rearrange the dimensions of a target tensor in a specified order

x_original = torch.rand(size=(224,224,3))  # [height, width, color_channels]

# Permue the original tensor to rearrange the axis (or DIM) order

x_permuted = x_original.permute(2, 0 ,1)   # shifts axis 0->1, 1->2, 2->0 Color_channel is put first

print (f"Previous shape: {x_original.shape}")
print(f"Newshape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
Newshape: torch.Size([3, 224, 224])


In [33]:
# Basically the permuted show a different view of the original tensor
# Even though the value in original tensor ws changed, but it was same as in permuted vector as well
x_original[1,0,0] = 3
x_original[1,0,0], x_permuted[0,1,0]

(tensor(3.), tensor(3.))

In [35]:
# Create a tensor

import torch

x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [36]:
# indexing

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [38]:
x[0][0]

tensor([1, 2, 3])

In [39]:
# Lets index on the midle bracket (dim=1)
x[0,0]

tensor([1, 2, 3])

In [40]:
# Lets index on the most inner bracket (last dim)
x[0][0][1]

tensor(2)

In [41]:
x[0][1][1]

tensor(5)

In [42]:
x[0][2][2x[0][0][1]]

tensor(9)

In [45]:
# You can use ":" to select all of target dim
x[:,0]

tensor([[1, 2, 3]])

In [46]:
x[:,:,0]

tensor([[1, 4, 7]])

In [47]:
x[:,:,1]

tensor([[2, 5, 8]])

In [48]:
x[:,1,1]

tensor([5])

### PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical comuting library.
And because of this, Pytorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray`
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()`

In [49]:
#NumPy arrayto tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor= torch.from_numpy(array) # when converting from numpy to pytorch, PyTorch reflects numpy default dtype of float64 instead of float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [51]:
# Change the value of array, what will this do to tensor?

array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [54]:
#Torch to Numpy

tensor = torch.ones(7)
numpy_tensor= tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducability (trying to take random out of random)

In short how a Neural Network learns:

`start with random numbers -> tensor operation -> update random numbers to try and make better representations of data -> again -> again ..`

To reduce randomness in Neural Networks and Pytorch comes the concept of a **random seed**.

Essentiallywhat the random seed does is "flavor" the randomness.

In [55]:
import torch
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

# Set the random seed again since if we dont set the seed again then it will reset
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running Tensor on GPU

In [57]:
import torch
torch.cuda.is_available()

False